[workspace]
channels = ["conda-forge", "https://conda.modular.com/max"]
name = "distributed-llama-mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
pyre = { cmd = "pyre" }

[dependencies]
mojo = ">=1.0.0b2,<2"
numpy = ">=1.24"
max = ">=0.1.0"
transformers = ">=5.14.1,<6"
pytorch = ">=2.12.1,<3"

[pypi-dependencies]
zeroconf = ">=0.150.0, <0.151"
