MSG_SHARD_SPEC = 0
MSG_READY = 1
MSG_FORWARD_DATA = 2
MSG_FORWARD_RESULT = 3
MSG_SHUTDOWN = 4
MSG_ATTN_OUTPUT = 5
MSG_FFN_RESULT = 6
MSG_INIT_WEIGHTS = 7
MSG_ALL_LAYERS_DONE = 8
MSG_DECODE_STEP = 9  # (layer_idx, h_norm) → worker computes FFN for seq_len=1 decode
